# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{h2o}
  s.version = "0.3.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Taylor luk"]
  s.date = %q{2011-03-14}
  s.description = %q{h2o is a django inspired template that offers natural template syntax and easy to integrate.}
  s.email = %q{subjective@gmail.com}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".autotest",
    ".project",
    "README.md",
    "Rakefile",
    "TODO.md",
    "VERSION",
    "benchmark/parser.rb",
    "benchmark/source.html",
    "example/erb/base.html",
    "example/h2o/base.html",
    "example/h2o/index.html",
    "example/h2o/inherit.html",
    "example/h2o/layout.html",
    "example/liquid/base.html",
    "example/request.html",
    "example/run.rb",
    "example/server",
    "example/server.bat",
    "example/server.rb",
    "h2o.gemspec",
    "init.rb",
    "lib/.DS_Store",
    "lib/core_ext/object.rb",
    "lib/h2o.rb",
    "lib/h2o/constants.rb",
    "lib/h2o/context.rb",
    "lib/h2o/datatype.rb",
    "lib/h2o/error.rb",
    "lib/h2o/file_loader.rb",
    "lib/h2o/filters.rb",
    "lib/h2o/filters/default.rb",
    "lib/h2o/nodes.rb",
    "lib/h2o/parser.rb",
    "lib/h2o/tags.rb",
    "lib/h2o/tags/block.rb",
    "lib/h2o/tags/extends.rb",
    "lib/h2o/tags/for.rb",
    "lib/h2o/tags/if.rb",
    "lib/h2o/tags/raw.rb",
    "lib/h2o/tags/with.rb",
    "lib/h2o/template.rb",
    "spec/fixtures/_partial.html",
    "spec/fixtures/a.html",
    "spec/fixtures/b.html",
    "spec/fixtures/deep/folder/c.html",
    "spec/h2o/context_spec.rb",
    "spec/h2o/default.html",
    "spec/h2o/file_loader_spec.rb",
    "spec/h2o/file_loader_spec.rbc",
    "spec/h2o/filters_spec.rb",
    "spec/h2o/parser_spec.rb",
    "spec/h2o/tags/block_spec.rb",
    "spec/h2o/tags/for_spec.rb",
    "spec/h2o/tags/if_spec.rb",
    "spec/h2o/tags/raw_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://www.h2o-template.org}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.0}
  s.summary = %q{h2o is a django inspired template}
  s.test_files = [
    "spec/h2o/context_spec.rb",
    "spec/h2o/file_loader_spec.rb",
    "spec/h2o/filters_spec.rb",
    "spec/h2o/parser_spec.rb",
    "spec/h2o/tags/block_spec.rb",
    "spec/h2o/tags/for_spec.rb",
    "spec/h2o/tags/if_spec.rb",
    "spec/h2o/tags/raw_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

