# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{h2o}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Taylor luk"]
  s.date = %q{2010-02-21}
  s.description = %q{h2o is a django inspired template that offers natural template syntax and easy to integrate.}
  s.email = %q{subjective@gmail.com}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".autotest",
     ".gitignore",
     ".project",
     "README.md",
     "Rakefile",
     "TODO.md",
     "VERSION",
     "benchmark/parser.rb",
     "benchmark/source.html",
     "example/erb/base.html",
     "example/h2o/base.html",
     "example/h2o/index.html",
     "example/h2o/inherit.html",
     "example/h2o/layout.html",
     "example/request.html",
     "example/run.rb",
     "example/server",
     "example/server.bat",
     "example/server.rb",
     "h2o.gemspec",
     "init.rb",
     "lib/.DS_Store",
     "lib/core_ext/object.rb",
     "lib/h2o.rb",
     "lib/h2o/constants.rb",
     "lib/h2o/context.rb",
     "lib/h2o/datatype.rb",
     "lib/h2o/filters.rb",
     "lib/h2o/filters/default.rb",
     "lib/h2o/nodes.rb",
     "lib/h2o/parser.rb",
     "lib/h2o/tags.rb",
     "lib/h2o/tags/block.rb",
     "lib/h2o/tags/for.rb",
     "lib/h2o/tags/if.rb",
     "lib/h2o/tags/with.rb",
     "spec/context_spec.rb",
     "spec/filters_spec.rb",
     "spec/parser_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/tags_spec.rb"
  ]
  s.homepage = %q{http://www.h2o-template.org}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{h2o is a django inspired template}
  s.test_files = [
    "spec/context_spec.rb",
     "spec/filters_spec.rb",
     "spec/parser_spec.rb",
     "spec/spec_helper.rb",
     "spec/tags_spec.rb",
     "spec/template_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

